#!/bin/bash

echo setupmongo time now: `date +"%T" `
until mongo --host 172.17.0.2:27017 <<EOF
  var config = {
    "_id" : "peakaboo",
    "members": [{"_id": 0,
                 "host":"127.0.0.1"
               }]
  };
EOF
do
  printf '.'
  sleep 1
done
