peakaboo:
  build: ..
  environment:
    - MONGO_URL=mongodb://peakabooMongo:27017/peakaboo
    - ROOT_URL=https://${SERVER_NAME}
    - STARTUP_DELAY=10
    - METEOR_SETTINGS
  links:
    - peakabooMongo
  restart: on-failure

peakabooMongoSetup:
  image: mongo:3
  links:
    - peakabooMongo
  volumes:
    - ./mongo:/scripts:ro
  entrypoint: [ "/scripts/setupmongo" ]

peakabooMongo:
  image: mongo:3
  volumes:
    - ./mongo/db:/data/db
  restart: on-failure
  ports:
    - "27017:27017"

peakaboonginx:
  build: https://github.com/androidwiltron/nginx-rtmp-docker.git
  command: /scripts/startnginx
  environment:
    - SERVER_NAME
  volumes:
    - ./nginx:/tmp/nginx
    - ./nginx/startnginx:/scripts/startnginx:ro
  links:
    - peakaboo
  ports:
    - "80:80"
    - "443:443"
    - "1935:1935"
  restart: on-failure
