version: "3"
services:
  peakaboo:
    build:
      context: ..
      args:
        - http_proxy
        - https_proxy
    environment:
      - MONGO_URL=mongodb://peakabooMongo:27017/peakaboo
      - ROOT_URL=https://${SERVER_NAME}
      - STARTUP_DELAY=10
      - METEOR_SETTINGS
      - https_proxy
      - http_proxy
    links:
      - peakabooMongo
    restart: always

  peakabooMongo:
    image: mongo:3
    volumes:
      - mongovol1:/data/db
    restart: always
    ports:
      - "27017:27017"

  peakabooNginx:
    image: nginx
    command: /scripts/startnginx
    environment:
      - SERVER_NAME
    volumes:
      - ./nginx:/tmp/nginx
      - ./nginx/startnginx:/scripts/startnginx:ro
    links:
      - peakaboo
    ports:
      - "80:80"
      - "443:443"
    restart: always

volumes:
  mongovol1:
